In [4]:
import pandas as pd
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [22]:
hv1 = pd.read_csv("../data/finished_data_files/hv1.csv", index_col = 0)
hv1 = hv1.T
hv1.columns = [f"hv1_{x}" for x in range(0, len(hv1.columns))]

In [23]:
hv1

,hv1_0,hv1_1,hv1_2,hv1_3,hv1_4,hv1_5,hv1_6,hv1_7,hv1_8,hv1_9,...,hv1_1147,hv1_1148,hv1_1149,hv1_1150,hv1_1151,hv1_1152,hv1_1153,hv1_1154,hv1_1155,hv1_1156
MT-CYB,33.0,11.0,41.0,16.0,39.0,55.0,40.0,26.0,52.0,38.0,...,16.0,9.0,48.0,25.0,24.0,29.0,99.0,49.0,27.0,21.0
MT-ND5,8.0,1.0,6.0,9.0,7.0,10.0,1.0,8.0,7.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-ND4,22.0,22.0,51.0,18.0,44.0,22.0,43.0,49.0,39.0,33.0,...,34.0,19.0,13.0,55.0,60.0,38.0,47.0,88.0,46.0,38.0
MT-ND4L,4.0,2.0,5.0,1.0,3.0,4.0,1.0,3.0,3.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-ND3,32.0,19.0,45.0,18.0,41.0,34.0,31.0,32.0,53.0,24.0,...,23.0,68.0,41.0,38.0,21.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CTC-209H22.3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CALCA,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RP11-290F5.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RP11-327F22.4,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AC093642.6,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
dress1 = pd.read_csv("../data/finished_data_files/dress1.csv", index_col = 0)
dress1 = dress1.T
dress1.columns = [f"dress1_{x}" for x in range(0, len(dress1.columns))]

In [31]:
dress1

,dress1_0,dress1_1,dress1_2,dress1_3,dress1_4,dress1_5,dress1_6,dress1_7,dress1_8,dress1_9,...,dress1_5631,dress1_5632,dress1_5633,dress1_5634,dress1_5635,dress1_5636,dress1_5637,dress1_5638,dress1_5639,dress1_5640
MT-CYB,103.0,72.0,32.0,81.0,48.0,82.0,190.0,164.0,42.0,124.0,...,67.0,94.0,20.0,123.0,121.0,93.0,67.0,38.0,14.0,141.0
MT-ND6,4.0,2.0,5.0,2.0,7.0,5.0,24.0,4.0,4.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-ND5,36.0,15.0,13.0,11.0,19.0,22.0,46.0,37.0,13.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-ND4,67.0,9.0,17.0,19.0,12.0,24.0,73.0,46.0,14.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-ND4L,146.0,34.0,21.0,41.0,40.0,37.0,165.0,109.0,28.0,98.0,...,79.0,40.0,22.0,18.0,5.0,103.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AC006960.7,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RP11-71N10.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CTC-459M5.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RP11-624L4.2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RP11-109D20.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
hv2 = pd.read_csv("../data/finished_data_files/hv2.csv", index_col = 0)
hv2 = hv2.T
hv2.columns = [f"hv2_{x}" for x in range(0, len(hv2.columns))]

In [33]:
hv3 = pd.read_csv("../data/finished_data_files/hv3.csv", index_col = 0)
hv3 = hv3.T
hv3.columns = [f"hv3_{x}" for x in range(0, len(hv3.columns))]

In [34]:
hv4 = pd.read_csv("../data/finished_data_files/hv4.csv", index_col = 0)
hv4 = hv4.T
hv4.columns = [f"hv4_{x}" for x in range(0, len(hv4.columns))]

In [35]:
hv5 = pd.read_csv("../data/finished_data_files/hv5.csv", index_col = 0)
hv5 = hv5.T
hv5.columns = [f"hv5_{x}" for x in range(0, len(hv5.columns))]

In [36]:
hv5

,hv5_0,hv5_1,hv5_2,hv5_3,hv5_4,hv5_5,hv5_6,hv5_7,hv5_8,hv5_9,...,hv5_1148,hv5_1149,hv5_1150,hv5_1151,hv5_1152,hv5_1153,hv5_1154,hv5_1155,hv5_1156,hv5_1157
MT-CYB,38.0,45.0,156.0,38.0,48.0,47.0,52.0,19.0,38.0,46.0,...,28.0,28.0,257.0,32.0,37.0,29.0,170.0,12.0,383.0,31.0
MT-ND6,2.0,4.0,30.0,1.0,5.0,10.0,3.0,3.0,4.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-ND5,5.0,13.0,43.0,9.0,13.0,31.0,7.0,13.0,12.0,18.0,...,50.0,6.0,89.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN
MT-ND4,19.0,22.0,69.0,40.0,24.0,27.0,25.0,17.0,10.0,8.0,...,31.0,256.0,20.0,28.0,15.0,88.0,8.0,150.0,17.0,NaN
MT-ND4L,41.0,42.0,110.0,65.0,30.0,66.0,35.0,23.0,23.0,33.0,...,33.0,30.0,19.0,125.0,7.0,231.0,35.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RP11-544M22.13,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CTC-558O19.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RP4-666F24.3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CTC-459M5.2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCDC181,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
concat_df = pd.concat([dress1, hv1.reindex(dress1.index)], axis = 1)
concat_df = pd.concat([concat_df, hv2.reindex(concat_df.index)], axis = 1)
concat_df = pd.concat([concat_df, hv3.reindex(concat_df.index)], axis = 1)
concat_df = pd.concat([concat_df, hv4.reindex(concat_df.index)], axis = 1)
concat_df = pd.concat([concat_df, hv5.reindex(concat_df.index)], axis = 1)

In [40]:
concat_df

,dress1_0,dress1_1,dress1_2,dress1_3,dress1_4,dress1_5,dress1_6,dress1_7,dress1_8,dress1_9,...,hv5_1148,hv5_1149,hv5_1150,hv5_1151,hv5_1152,hv5_1153,hv5_1154,hv5_1155,hv5_1156,hv5_1157
MT-CYB,103.0,72.0,32.0,81.0,48.0,82.0,190.0,164.0,42.0,124.0,...,28.0,28.0,257.0,32.0,37.0,29.0,170.0,12.0,383.0,31.0
MT-ND6,4.0,2.0,5.0,2.0,7.0,5.0,24.0,4.0,4.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT-ND5,36.0,15.0,13.0,11.0,19.0,22.0,46.0,37.0,13.0,30.0,...,50.0,6.0,89.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN
MT-ND4,67.0,9.0,17.0,19.0,12.0,24.0,73.0,46.0,14.0,36.0,...,31.0,256.0,20.0,28.0,15.0,88.0,8.0,150.0,17.0,NaN
MT-ND4L,146.0,34.0,21.0,41.0,40.0,37.0,165.0,109.0,28.0,98.0,...,33.0,30.0,19.0,125.0,7.0,231.0,35.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AC006960.7,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RP11-71N10.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CTC-459M5.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RP11-624L4.2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RP11-109D20.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
concat_df.to_csv("../data/GSEA_df.csv")

In [52]:
#lets also make a pd series for annotating the sample HV or dress
samples = list(concat_df.columns)
sample_df= pd.DataFrame(index=samples)

samplelist = []
for i in samples:
    if i.startswith("dress"):
        samplelist.append("DRESS")
    else:
        samplelist.append("HV")
        
sample_df["sample"] = samplelist
sample_df

         sample
dress1_0  DRESS
dress1_1  DRESS
dress1_2  DRESS
dress1_3  DRESS
dress1_4  DRESS
...         ...
hv5_1153     HV
hv5_1154     HV
hv5_1155     HV
hv5_1156     HV
hv5_1157     HV

[16374 rows x 1 columns]

In [54]:
sample_df.to_csv("../data/GSEA_samples.csv")